namespace: staging

image:
  tag: "latest"
  pullPolicy: IfNotPresent

application:
  replicas: 2

ingress:
  enabled: true
  host: staging.example.com
  scheme: internet-facing
  targetType: ip

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  cpuUtilization: 70
  memoryUtilization: 80

postgres:
  enabled: true
  database: ecommerce
  username: ecommerce
  password: CHANGE_ME
  storage:
    size: 20Gi
    storageClassName: gp3

redis:
  enabled: true

loadgenerator:
  enabled: false
