{{- if and .Values.redis.enabled .Values.redis.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
{{- end }}
